#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    guifont = "SourceCodePro Nerd Font Mono:h11"

    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = 'arrow'
    statusline_iseparator = 'arrow'
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = true
    statusline_unicode_symbols = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
    enable_neomake = false
    enable_ale = true
    lint_on_the_fly = true 
    # left sections of statusline
    statusline_left_sections = [
       'winnr',
       'major mode',
       'filename',
       'fileformat',
       'minor mode lighters',
       'version control info',
       'search status',
       'test'
    ]
    # right sections of statusline
    statusline_right_sections = [
       'cursorpos',
       'percentage',
       'input method',
       'date',
       'time',
       'test' 
    ]
    autocomplete_method = "deoplete"
# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"
[[layers]]
name = 'lang#python'
[[layers]]
name = 'default'
[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30
[[layers]]
name = "VersionControl"
[[layers]]
name = "git" 
git-plugin = "fugitive"
[[layers]]
name = "debug"
[[layers]]
name = 'tmux'
[[layers]]
name = "core#statusline"
[[custom_plugins]]
repo = 'cjrh/vim-conda'
merge = false
[[layers]]
name = 'leaderf'
[[layers]]
name = 'checkers'
[[custom_plugins]]
repo = 'roxma/nvim-yarp'
merge = false
[[custom_plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
merge = false
[[custom_plugins]]
repo =  'arnoudbuzing/wolfram-vim'
merge = false
